FROM php:8.2-apache

# Actualizar e instalar dependencias limpiando el caché al final
RUN apt-get update && apt-get install -y \
    unzip \
    git \
    curl \
    libzip-dev \
    zip \
    && docker-php-ext-install zip mysqli pdo pdo_mysql \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN a2enmod rewrite
RUN chown -R www-data:www-data /var/www/html