version: "3.9"

services:
  # -----------------------------
  # PHP + PHPUnit + Xdebug
  # -----------------------------
  phpunit:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: phpunit-app
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - XDEBUG_MODE=coverage
    command:
      - sh
      - -c
      - "git config --global --add safe.directory /app; php bin/cache_routes.php; php bin/cache_dtos.php; tail -f /dev/null"

  # -----------------------------
  # LAMP Stack (Apache + PHP + MySQL en RAM) (http://localhost:8080)
  # -----------------------------
  lamp:
    image: mattrayner/lamp:latest-2004-php8
    container_name: lamp-app
    ports:
      - "8080:80"       # Apache
      - "3307:3306"     # MySQL
    volumes:
      - ./:/var/www/html
      - ./apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    tmpfs:
      - /var/lib/mysql  # MySQL en RAM
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: balero_cms
    restart: unless-stopped

  # -----------------------------
  # PhpMyAdmin (http://localhost:8081)
  # -----------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: lamp
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ""
      PMA_ARBITRARY: 1
    depends_on:
      - lamp

  # -----------------------------
  # SonarQube
  # -----------------------------
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    depends_on:
      - db
    restart: unless-stopped

  # -----------------------------
  # PostgreSQL para SonarQube
  # -----------------------------
  db:
    image: postgres:15
    container_name: postgres-sonar
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: